5 fórmulas entrenamiento
maestre7/DataSciToolbox pull request #18
Opened 2023-07-04 20:01 UTC by XaviAlbert

Decision Tree, Knn, Linear Regression, Random Forest y SVR

2023-07-04 20:11 UTC, GiamoSalerno requested changes
En los tets, no tienes que usar lo de ejecutar el test. 
Tengo entendido que se ejecutan todos a la vez por terminal;

Lo que sí tienes que hacer en cada uno de los archivos es importar pytest.

2023-07-04 20:26 UTC, JuditRoca reviewed
en principio veo lo mismo que Giaco, el resto parece ok.

2023-07-05 07:12 UTC, GiamoSalerno approved these changes

2023-07-05 11:54 UTC, juanmendiz approved these changes

2023-07-05 12:34 UTC, juanmendiz approved these changes

2023-07-05 15:28 UTC, JuditRoca commented
arreglado desde otra pull

2023-07-05 15:28 UTC, closed without merging