J5xu um ev
maestre7/DataSciToolbox pull request #6
Opened 2023-07-04 17:31 UTC by GabrielaRomina

Funcion segmentar para crear dataframes de menor tamaño

2023-07-04 18:19 UTC, GiamoSalerno approved these changes

2023-07-04 19:58 UTC, AlexCapis reviewed
revisado

2023-07-04 20:00 UTC, maestre7 requested changes

2023-07-04 20:00 UTC, maestre7 commented on test/test_segmentar_y_guardar.py
> +sys.path.append(root_dir)
haz merge desde dev actualizado y estas dos líneas te sobraran

2023-07-04 20:00 UTC, maestre7 commented on test/test_segmentar_y_guardar.py
> +
solo prepocessing

2023-07-04 20:00 UTC, maestre7 commented on src/preprocessing.py
> +def segmentar_y_guardar(df, num_segmentos, output_folder):
el typing

2023-07-04 20:03 UTC, GabrielaRomina commented on test/test_segmentar_y_guardar.py
> +sys.path.append(root_dir)
Gracias... después de cenar reviso todo y lo dejo listo

2023-07-05 08:40 UTC, GiamoSalerno requested changes

2023-07-05 08:40 UTC, GiamoSalerno commented on test/test_calcular_edad.py
> +
Hay que quitar el src y subir esta línea con el resto de los imports.

2023-07-05 08:49 UTC, maestre7 commented on test/test_calcular_edad.py
> +
al final si q hace falta el src.

2023-07-05 08:52 UTC, GiamoSalerno commented on test/test_calcular_edad.py
> +
No me jodas, después de haberlos quitado?

2023-07-05 10:34 UTC, GabrielaRomina commented on test/test_calcular_edad.py
> +
modificado y puesto el src

2023-07-05 10:42 UTC, GiamoSalerno approved these changes

2023-07-05 13:08 UTC, AlexCapis approved these changes

2023-07-05 14:08 UTC, merged