f.export.model
maestre7/DataSciToolbox pull request #8
Opened 2023-07-04 18:08 UTC by JuditRoca

funcion para exportacion e importacion de modelos entrenados.

2023-07-04 19:21 UTC, GiamoSalerno requested changes
Recuerda el try-except

2023-07-04 19:43 UTC, JuditRoca commented
listo!

2023-07-04 19:52 UTC, GiamoSalerno reviewed
He visto que has eliminado la línea de la función que tenía las descripciones, por ejemplo, :str, :bool y demás. 
¿No sería mejor con eso?

2023-07-04 19:56 UTC, maestre7 commented on src/modeling.py
> +    return model_pretrained
Esto esta fuera del if te dará problemas si no entra en open

2023-07-04 22:22 UTC, JuditRoca commented on src/modeling.py
> +    return model_pretrained
gracias, no me di cuen. Arreglado!

2023-07-05 07:11 UTC, GiamoSalerno approved these changes

2023-07-05 08:28 UTC, closed without merging